#!/bin/bash

cd ~/src/multi-dig && git stash && git pull

if [[ -z $(head -n1 ~/src/multi-dig/mdig | grep 'Cellar') ]]; then
	which brew &>/dev/null
	if [[ $? -eq 0 ]]; then
		echo "autofixing"
		brewbash=$(brew list bash | egrep '/bash$')
		sed -ri '1 s,^.+$,#!'"$brewbash"',' ~/src/multi-dig/mdig
	else
		echo "manually fix shebang in mdig"
	fi
else
	head -n1 ~/src/multi-dig/mdig
fi
